### ISSUE TITLE
No entry or class found for 'log.handlers

### ISSUE THREAD

**Issue by Mela** [matomo-org/plugin-Migration#21]
Hello,
when running the migration on the command line, I'm getting the following error. First I thought maybe the Pear-Log-Package was missing from the server, but I've checked with the hosting provider and it is present. 

`PHP Fatal error:  Uncaught DI\NotFoundException: No entry or class found for 'log.handlers' in /www/htdocs/w01a420d/mela.geekgirls.de/wp-content/plugins/matomo/app/vendor/php-di/php-di/src/DI/Container.php:128
Stack trace:
#0 /www/htdocs/w01a420d/mela.geekgirls.de/wp-content/plugins/matomo/app/core/Container/StaticContainer.php(80): DI\Container->get('log.handlers')
#1 /www/htdocs/w01a420d/mela.geekgirls.de/wp-content/plugins/matomo/app/core/Console.php(71): Piwik\Container\StaticContainer::get('log.handlers')
`

I ran the command with and without the --skip-logs option. 

Any ideas?

Regards,
Mela

**Comment by tsteur** [comment]
Thanks for mentioning this @Mela 

I've fixed this particular error in https://github.com/matomo-org/wp-matomo/commit/11ca501b414a2bf4d333aae57bf4276a2bb40421 and it will be included in the next update of our Matomo plugin. If you are familiar with editing files on your WordPress manually you can fix it by making the same change in the file `wp-content/plugins/matomo/config/config.php` (add a new line containing `'log.handlers' => array(), `.

You would have gotten this error because more than likely a parameter was forgotten to be specified. Eg once I fixed this error, I got to see the actual error eg 

![image](https://user-images.githubusercontent.com/273120/87476367-5d30a400-c67a-11ea-8d50-f4517209270c.png)
