### ISSUE TITLE
Missing columns in the source DB table

### ISSUE THREAD

**Issue by errotu** [matomo-org/plugin-Migration#58]
I am trying to migrate from Matomo for WordPress (4.15.0) to Matomo On-Premise (v4.15.1), but receive the following error message:

> The following columns are missing in the source DB table "xyz_matomo_log_conversion": pageviews_before
>                                                                                                                            
>   [Exception]                                                                                                              
>   Please make sure both Matomo instances are on the same version and have the same plugins and plugin versions installed.  

How should I deal best with it? Should I remove the column from the target database, or should I add it (how exactly) to the source database?

Thanks a lot for your help!

**Comment by snake14** [comment]
Hi @errotu . Sorry that you're experiencing this issue. Looks like that column was created for Matomo 4.14.0. I'm not quite sure why it didn't get added to your source database. I think that you should be fine adding [the column](https://github.com/matomo-org/matomo/blob/5.x-dev/core/Db/Schema/Mysql.php#L244) to your source database since it defaults to null.

The following should do the trick as long as you change the table prefix/name to match yours:
```
ALTER TABLE `matomo_log_conversion`
ADD COLUMN `pageviews_before` SMALLINT UNSIGNED DEFAULT NULL;
```

I'm going to go ahead and close this issue, but please let me know if you feel it should be re-opened for any reason.

**Comment by errotu** [comment]
Worked perfectly, thanks a lot!
